### ISSUE TITLE
The stack fails

### ISSUE THREAD

**Issue by kolizo12** [awslabs/cost-optimization-monitor#2]
Issue Description: This template resource fails at resource ProxyServer1 with this error "error: urllib3 1.8.2 is installed but urllib3<1.24,>=1.20 is required by set(['botocore'])" 
workaround:- 

"install_awsdbrparser": { 
"commands": { 
"0-git_clone": { 
"command": "git clone https://github.com/awslabs/aws-detailed-billing-parser.git" , 
"cwd": "/home/ec2-user" 
}, 
"0-python_setup": { 
"command": "pip install urllib3==1.23" 
}, 
"1-python_setup": { 
"command": "python setup.py install", 
"cwd": "/home/ec2-user/aws-detailed-billing-parser" 
}, 
"2-dbr_setup": { 
"command": "/tmp/setup.dbr", 
"cwd": "/home/ec2-user" 
} 
} 
}, 
Added 0-python_setup with "command": "pip install urllib3==1.23". 

Please let me know if you need anymore information on this issue.

**Comment by hnishar** [comment]
Thanks for reporting the issue, feel free to submit the pull request for this change

**Comment by pestir** [comment]
fixes issue

**Comment by shsenior** [comment]
Version 1.1.0 update
