### ISSUE TITLE
What is the range for proxy server for nginx. 

### ISSUE THREAD

**Issue by murali741** [awslabs/cost-optimization-monitor#4]
20:46:32 UTC-0400 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | kibanabillboard | The following resource(s) failed to create: [ProxyServer1]. . Rollback requested by user.
-- | -- | -- | -- | --
  | 20:46:32 UTC-0400 | CREATE_FAILED | AWS::EC2::Instance | ProxyServer1 | Failed to receive 1 resource signal(s) within the specified duration

**Comment by shsenior** [comment]
Version 1.1.0 update
