### ISSUE TITLE
Failed to receive 1 resource signal for ProxyServer1

### ISSUE THREAD

**Issue by sriramgk** [awslabs/cost-optimization-monitor#5]
There is no issue in the ProxyServer2. But I am getting the below error for ProxyServer1. There are differences between ProxyServer1 and ProxyServer2 in the CF template. If both the servers come under the ELB, both the servers should be in the same setup. Please correct me if I am wrong.

> 02 May 2019 18:04:14 | ProxyServer1 | CREATE_FAILED | Failed to receive 1 resource signal(s) within the specified duration

**Comment by sriramgk** [comment]
I SSH into the ProxyServer1 and found the below error.

```
[ec2-user@ip-10-250-250-20 ~]$ sudo /opt/aws/bin/cfn-init -v --stack CostReportSriram --resource ProxyServer1 --configsets Monitor_install --region ap-northeast-2
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 891, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 69: ordinal not in range(128)
Logged from file util.py, line 476
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 891, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 49: ordinal not in range(128)
Logged from file util.py, line 476
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 891, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 71: ordinal not in range(128)
Logged from file util.py, line 476
Error occurred during build: Command 1-python_setup failed
```


But if I ran both `1-python_setup` manually I got success.
`python setup.py install`
`pip install es_tools-0.1.4.tar.gz`

Hope there is no issue in the "aws-detailed-billing-parser" and "es_tools-0.1.4.tar.gz" packages. Not sure what is causing this issue.

**Comment by shsenior** [comment]
Version 1.1.0 update
