### ISSUE TITLE
Does this support CUR?

### ISSUE THREAD

**Issue by bazimov** [awslabs/cost-optimization-monitor#8]
As far as we know DBR has been deprecated. Does this tool currently support CUR as well? I cannot find from the documentation if it does.

**Comment by koiker** [comment]
No, this tool only works with DBR files.

To work with CUR we have those options:
For more information about creating an Amazon S3 bucket and using Athena to query your data, see [Querying Cost and Usage Reports Using Amazon Athena.](https://docs.aws.amazon.com/cur/latest/userguide/cur-query-athena.html)

For more information about uploading to Amazon Redshift, see [Loading Report Data to Amazon Redshift.](https://docs.aws.amazon.com/cur/latest/userguide/cur-query-other.html#cur-query-other-rs)

For more information about uploading to Amazon QuickSight, see [Loading Report Data to Amazon QuickSight.](https://docs.aws.amazon.com/cur/latest/userguide/cur-query-other.html#cur-query-other-qs)

Reference: https://docs.aws.amazon.com/cur/latest/userguide/what-is-cur.html

**Comment by knihit** [comment]
Hi @bazimov , thank you for reaching out, Hope @koiker clarified. If you have any questions please let us know.

**Comment by bazimov** [comment]
Thank you very much. I got my answer.
